name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Check formatting
        uses: rsookram/ktfmt-action@v1
        with:
          style: kotlinlang

      - name: Lint
        run: ./gradlew lintRelease

      - name: Test
        run: ./gradlew testDebug

      - name: Build
        run: ./gradlew assembleRelease
